services:
  postgres:
    image: postgres:15-bullseye
    container_name: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=789456123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cashly
      - POSTGRES_PORT=5432
    networks:
      - cashly_network

networks:
  cashly_network:
    driver: bridge
